name: rebuild-docker

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up additional packages
        run: |
          sudo apt update
          sudo apt install -y ca-certificates parted wget xz-utils
      - name: Run builder
        run: sudo ./builder/base_test.sh
