name: rebuild-docker

on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up additional packages
        run: |
          sudo apt update
          sudo apt install -y ca-certificates parted wget xz-utils zip
      - name: Run builder
        run: sudo ./builder/imgbuild.sh
      - name: Compress the image
        run: |
          sudo chmod a+rw ./images/*
          cd ./images && zip ./ubuntu-20.04.2-preinstalled-server-arm64+raspi.img.zip ./ubuntu-20.04.2-preinstalled-server-arm64+raspi.img
